language: go
os:
  - linux
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
script:
  - gofmt -l ./
  - go vet -v ./...
  - docker-compose -f dev-compose.yml up --build cassandra-primary cassandra
  - sleep 30
  - docker-compose -f dev-compose.yml up --build tests
