version: "3"
services:
  hord:
    build: .
    ports:
      - "443:8443"
      - "9000:9000"
    depends_on:
      - cassandra
      - cassandra-primary
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    command: --debug --database=cassandra-primary --database=cassandra -k hord
  tests:
    build: .
    depends_on:
      - cassandra
      - cassandra-primary
    command: /bin/bash -c "sleep 60 && go test -v ./..."
  cassandra-primary:
    image: madflojo/cassandra:latest
    command: /bin/bash -c "sleep 1 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_KEYSPACE=hord
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    deploy:
      restart_policy:
        condition: always
  cassandra:
    image: madflojo/cassandra:latest
    command: /bin/bash -c "sleep 15 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-primary
      - CASSANDRA_KEYSPACE=hord
    depends_on:
      - cassandra-primary
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    deploy:
      replicas: 2
      restart_policy:
        condition: always
