version: "3"
services:
  hord:
    build: .
    ports:
      - "443:8443"
      - "9000:9000"
    depends_on:
      - cassandra
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: always
  tests:
    build: .
    depends_on:
      - cassandra
    command: go test -v ./...
  cassandra:
    image: cassandra:latest

